ALTER TABLE recon_ods_cash_expected ALTER COLUMN order_no DROP NOT NULL;
ALTER TABLE discrepancy ALTER COLUMN type TYPE VARCHAR(32);
COMMENT ON COLUMN recon_run.tenant_id IS '业务租户；权益 ODS 扫描的强制隔离键';
COMMENT ON COLUMN discrepancy.measure_kind IS '度量类型：MONEY 或 QUANTITY';
COMMENT ON COLUMN discrepancy.expected_quantity IS '非金额权益应发数量';
COMMENT ON COLUMN discrepancy.internal_quantity IS '非金额权益内部发放数量';
COMMENT ON COLUMN discrepancy.provider_quantity IS '非金额权益供应商履约数量';
COMMENT ON COLUMN discrepancy.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN discrepancy.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN discrepancy.benefit_order_no IS '权益订单号';
COMMENT ON COLUMN recon_ods_cash_expected.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN recon_ods_cash_expected.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN recon_ods_cash_expected.benefit_order_no IS '权益订单号；应发阶段可为空';
COMMENT ON COLUMN recon_ods_cash_accounting.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN recon_ods_cash_accounting.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN recon_ods_cash_accounting.benefit_order_no IS '权益订单号';
COMMENT ON COLUMN recon_ods_cash_channel.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN recon_ods_cash_channel.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN recon_ods_cash_channel.benefit_order_no IS '权益订单号';
COMMENT ON COLUMN recon_ods_entitlement_expected.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN recon_ods_entitlement_expected.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN recon_ods_entitlement_expected.benefit_order_no IS '权益订单号；应发阶段可为空';
COMMENT ON COLUMN recon_ods_entitlement_internal.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN recon_ods_entitlement_internal.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN recon_ods_entitlement_internal.benefit_order_no IS '权益订单号';
COMMENT ON COLUMN recon_ods_entitlement_provider.expected_source_system IS '应发事实来源系统';
COMMENT ON COLUMN recon_ods_entitlement_provider.marketing_source_request_id IS '营销跨系统幂等请求号';
COMMENT ON COLUMN recon_ods_entitlement_provider.benefit_order_no IS '权益订单号';
